config/routes.rb
Rails.application.routes.draw do
  resources :traits

  resources :trait_types

end

app/models/trait.rb
class Trait < ActiveRecord::Base
  belongs_to :trait_type
end

app/models/trait_type.rb
class TraitType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trait_types_controller.rb
class TraitTypesController < ApplicationController
  before_action :set_trait_type, only: [:show, :edit, :update, :destroy]

  # GET /trait_types
  # GET /trait_types.json
  def index
    @trait_types = TraitType.all
  end

  # GET /trait_types/1
  # GET /trait_types/1.json
  def show
  end

  # GET /trait_types/new
  def new
    @trait_type = TraitType.new
  end

  # GET /trait_types/1/edit
  def edit
  end

  # POST /trait_types
  # POST /trait_types.json
  def create
    @trait_type = TraitType.new(trait_type_params)

    respond_to do |format|
      if @trait_type.save
        format.html { redirect_to @trait_type, notice: 'Trait type was successfully created.' }
        format.json { render :show, status: :created, location: @trait_type }
      else
        format.html { render :new }
        format.json { render json: @trait_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trait_types/1
  # PATCH/PUT /trait_types/1.json
  def update
    respond_to do |format|
      if @trait_type.update(trait_type_params)
        format.html { redirect_to @trait_type, notice: 'Trait type was successfully updated.' }
        format.json { render :show, status: :ok, location: @trait_type }
      else
        format.html { render :edit }
        format.json { render json: @trait_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trait_types/1
  # DELETE /trait_types/1.json
  def destroy
    @trait_type.destroy
    respond_to do |format|
      format.html { redirect_to trait_types_url, notice: 'Trait type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trait_type
      @trait_type = TraitType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trait_type_params
      params.require(:trait_type).permit(:name, :display, :description)
    end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  before_action :set_trait, only: [:show, :edit, :update, :destroy]

  # GET /traits
  # GET /traits.json
  def index
    @traits = Trait.all
  end

  # GET /traits/1
  # GET /traits/1.json
  def show
  end

  # GET /traits/new
  def new
    @trait = Trait.new
  end

  # GET /traits/1/edit
  def edit
  end

  # POST /traits
  # POST /traits.json
  def create
    @trait = Trait.new(trait_params)

    respond_to do |format|
      if @trait.save
        format.html { redirect_to @trait, notice: 'Trait was successfully created.' }
        format.json { render :show, status: :created, location: @trait }
      else
        format.html { render :new }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traits/1
  # PATCH/PUT /traits/1.json
  def update
    respond_to do |format|
      if @trait.update(trait_params)
        format.html { redirect_to @trait, notice: 'Trait was successfully updated.' }
        format.json { render :show, status: :ok, location: @trait }
      else
        format.html { render :edit }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traits/1
  # DELETE /traits/1.json
  def destroy
    @trait.destroy
    respond_to do |format|
      format.html { redirect_to traits_url, notice: 'Trait was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trait
      @trait = Trait.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trait_params
      params.require(:trait).permit(:name, :display, :description, :trait_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trait_types_helper.rb
module TraitTypesHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Algorithm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trait_types/_form.html.erb
<%= form_for(@trait_type) do |f| %>
  <% if @trait_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trait_type.errors.count, "error") %> prohibited this trait_type from being saved:</h2>

      <ul>
      <% @trait_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.text_field :display %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trait_types/edit.html.erb
<h1>Editing trait_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @trait_type %> |
<%= link_to 'Back', trait_types_path %>

app/views/trait_types/index.html.erb
<h1>Listing trait_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Display</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trait_types.each do |trait_type| %>
      <tr>
        <td><%= trait_type.name %></td>
        <td><%= trait_type.display %></td>
        <td><%= trait_type.description %></td>
        <td><%= link_to 'Show', trait_type %></td>
        <td><%= link_to 'Edit', edit_trait_type_path(trait_type) %></td>
        <td><%= link_to 'Destroy', trait_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trait type', new_trait_type_path %>

app/views/trait_types/new.html.erb
<h1>New trait_type</h1>

<%= render 'form' %>

<%= link_to 'Back', trait_types_path %>

app/views/trait_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trait_type.name %>
</p>

<p>
  <strong>Display:</strong>
  <%= @trait_type.display %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trait_type.description %>
</p>

<%= link_to 'Edit', edit_trait_type_path(@trait_type) %> |
<%= link_to 'Back', trait_types_path %>

app/views/traits/_form.html.erb
<%= form_for(@trait) do |f| %>
  <% if @trait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trait.errors.count, "error") %> prohibited this trait from being saved:</h2>

      <ul>
      <% @trait.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.text_field :display %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :trait_type_id %><br>
    <%= f.collection_select :trait_type_id, TraitType.all, :id, :name, :include_blank => true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traits/edit.html.erb
<h1>Editing trait</h1>

<%= render 'form' %>

<%= link_to 'Show', @trait %> |
<%= link_to 'Back', traits_path %>

app/views/traits/index.html.erb
<h1>Listing traits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Display</th>
      <th>Description</th>
      <th>Trait type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traits.each do |trait| %>
      <tr>
        <td><%= trait.name %></td>
        <td><%= trait.display %></td>
        <td><%= trait.description %></td>
        <td><%= trait.trait_type.display %></td>
        <td><%= link_to 'Show', trait %></td>
        <td><%= link_to 'Edit', edit_trait_path(trait) %></td>
        <td><%= link_to 'Destroy', trait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trait', new_trait_path %>

app/views/traits/new.html.erb
<h1>New trait</h1>

<%= render 'form' %>

<%= link_to 'Back', traits_path %>

app/views/traits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trait.name %>
</p>

<p>
  <strong>Display:</strong>
  <%= @trait.display %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trait.description %>
</p>

<p>
  <strong>Trait type:</strong>
  <%= @trait.trait_type.name %>
</p>

<%= link_to 'Edit', edit_trait_path(@trait) %> |
<%= link_to 'Back', traits_path %>